openapi: 3.1.0
info:
  title: Swagger Petstore - OpenAPI 3.1
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.1 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)

  termsOfService: https://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://petstore31.swagger.io/api/v3
    x-internal: false
tags:
  - name: user
    description: Operations about user
paths:
  /user/{username}:
    get:
      tags:
        - user
      summary: Get user by user name.
      description: Get user details based on username.
      operationId: getUserByName
      security:
        - api_key: []
      parameters:
        - name: username
          in: path
          description: The name that needs to be fetched. Use user1 for testing
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          headers:
            Access-Control-Allow-Origin:
              description: CORS header
              schema:
                type: string
                pattern: '.*'
                minLength: 1
                maxLength: 100
            X-RateLimit-Limit:
              description: The number of requests allowed in the current period
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 1000
            X-RateLimit-Remaining:
              description: The number of requests remaining in the current period
              schema:
                type: integer
                format: int32
                minimum: 0
                maximum: 1000
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    UserCurrencyExchange:
      type: object
      required:
        - date
        - currency
        - buyRate
        - sellRate
      properties:
        date:
          type: string
          format: date
          description: Date of the exchange rate
          example: "2025-10-01"
        currency:
          type: string
          description: Currency code
          example: "USD"
        buyRate:
          type: number
          format: double
          description: Buy rate (compra) for USD to PEN
          example: 3.72
        sellRate:
          type: number
          format: double
          description: Sell rate (venta) for USD to PEN
          example: 3.75

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          maximum: 9223372036854775807
          examples: [10]
        currencyExchange:
          $ref: '#/components/schemas/UserCurrencyExchange'
        username:
          type: string
          pattern: '^[a-zA-Z0-9_.-]{3,50}$'
          minLength: 3
          maxLength: 50
          examples: [theUser]
        firstName:
          type: string
          pattern: '^[a-zA-Z0-9_.-]{3,50}$'
          minLength: 3
          maxLength: 50
          examples: [John]
        lastName:
          type: string
          pattern: '^[a-zA-Z0-9_.-]{3,50}$'
          minLength: 3
          maxLength: 50
          examples: [James]
        email:
          type: string
          format: email
          pattern: '^[\w.-]+@([\w-]+\.)+[\w-]{2,4}$'
          minLength: 5
          maxLength: 100
          examples: [john@email.com]
        password:
          type: string
          minLength: 8
          maxLength: 20
          pattern: '^[a-zA-Z0-9_.-]{8,20}$'
          examples: ['12345']
        phone:
          type: string
          pattern: '^[0-9]{9}$'
          minLength: 9
          maxLength: 9
          examples: ['9001234567']
        userStatus:
          type: integer
          minimum: 1
          maximum: 10
          description: User Status
          format: int32
          examples: [1]
    Error:
      type: object
      properties:
        code:
          type: string
          pattern: '^[A-Z]{2}[0-9]{7}$'
          minLength: 8
          maxLength: 8
          examples: ['K0000404']
        message:
          type: string
          enum: ['User not found']
          examples: ['User not found']
      required:
        - code
        - message
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
